name: Laravel Deployment
on:
  push:
    branches:
      - master  # Adjust branch if necessary
      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: escargo
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         path: escargo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Upload built assets as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: public/build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}
          script: |
            cd /home/u763080638/domains/officetourisme.cd/escargo/
            git pull origin master
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear
            mv public/build ../public-html/build